name: Test

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
        
    - name: Install dependencies
      run: go get github.com/SchneePingu/karamuc/lib

    - name: Build
      run: go build github.com/SchneePingu/karamuc/lib

    - name: Test
      run: go test github.com/SchneePingu/karamuc/tests
